file = open("homework4.txt", "r", encoding = "utf-8")
s = file.readlines()
print(s)
file.close()
file_new = open("data.txt", "w", encoding = "utf-8")
file_new.write("Один - 1\n")
file_new.write("Два - 2\n")
file_new.write("Три - 3\n")
file_new.write("Четыре - 4\n")